- name: Incluindo servidor no domínio sifra.local
  hosts: ip ou hostname
  gather_facts: no
  tasks:
  - win_domain_membership:
      dns_domain_name: dominio.local
      hostname: opisifra26
      domain_admin_user: user_windows@dominio.local
      domain_admin_password: senha
      domain_ou_path: "OU=Server - Geral,OU=Computers - All,DC=dominio,DC=local"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required