---

  - name: Install Zabbix {{ zabbix_agent_base_version }} repo
    become: yes
#    yum:
#      name: http://repo.zabbix.com/zabbix/{{ zabbix_agent_base_version }}/rhel/6/{{ ansible_architecture }}/zabbix-agent-{{ zabbix_agent_version }}.el6.{{ ansible_architecture }}.rpm
#      state: present
    command: rpm -ivh http://repo.zabbix.com/zabbix/{{ zabbix_agent_base_version }}/rhel/6/{{ ansible_architecture }}/zabbix-agent-{{ zabbix_agent_version }}.el6.{{ ansible_architecture }}.rpm
    tags:
      - zabbix-agent

  - name: Installing Zabbix Agent {{ zabbix_agent_base_version }}
    become: yes
    yum:
      name: zabbix-agent
      state: latest
    tags:
      - zabbix-agent

  - name: Configure Zabbix Agent {{ zabbix_agent_base_version }}
    become: yes
    template:
      src: zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
    notify:
      - restart zabbix-agent
    tags:
      - zabbix-agent

  - name: Enable automatically starting zabbix-agent
    become: yes
    service:
      name: zabbix-agent
      state: started
      enabled: yes
